cmake_minimum_required(VERSION 3.6)

include(ExternalProjectUtils)

set_external_library(nghttp2_static FALSE)

if(NOT EXISTS ${LIBRARY_PATH})
    set_library_path(nghttp2_static NGHTTP2_PATH "")

    set(EXTERNAL_DEPENDENCY external_nghttp2)

    ExternalProject_Add(${EXTERNAL_DEPENDENCY}
            PREFIX ${EXTERNAL_LIBRARIES_BUILD_PATH}
			DOWNLOAD_COMMAND ${CMAKE_COMMAND} -DREFERENCE=${GIT_REFERENCE} -DREPO=${nghttp2_URL} -DBRANCH=${nghttp2_VERSION} -DSOURCE_DIR=${EXTERNAL_LIBRARIES_SOURCE_PATH}/nghttp2 -P ${CMAKE_CURRENT_LIST_DIR}/CloneRepository.cmake
            UPDATE_COMMAND ""
            SOURCE_DIR "${EXTERNAL_LIBRARIES_SOURCE_PATH}/nghttp2"
            CMAKE_ARGS ${COMMON_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} -DENABLE_STATIC_LIB=ON -DSTATIC_LIB_SUFFIX=_static -DENABLE_SHARED_LIB=OFF -DENABLE_PYTHON_BINDINGS=OFF -DENABLE_EXAMPLES=OFF -DINSTALL_DESTINATION=include/nghttp2 -DCMAKE_PREFIX_PATH=${EXTERNAL_LIBRARIES_INSTALL_PATH} -DCMAKE_INSTALL_PREFIX=${EXTERNAL_LIBRARIES_INSTALL_PATH}
            BUILD_BYPRODUCTS ${NGHTTP2_PATH}
            LIST_SEPARATOR ^^
            )
endif(NOT EXISTS ${LIBRARY_PATH})

expose_external_library(STATIC)
